os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\easy-cpp-print

platform: x64
configuration: Release

install:

build_script:
  - cd build
  - cmake --build . --target ALL_BUILD
  - ctest -C Release --verbose .

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" ..

after_build:
  - cd c:\projects\easy-cpp-print\build
