os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\easy-cpp-print

platform: x64
configuration: Release

install:

build:
  project: ALL_BUILD.vcxproj

before_build:
  - echo Downloading boost...
  - cd c:\projects\easy-cpp-print
  - cd include
  - wget -O boost.tar.bz2 "http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.60.0%2F&ts=1461928773&use_mirror=heanet"
  - tar xjf boost.tar.bz2
  - cd boost_1_60_0
  - mv boost ..
  - cd ../..
  - echo Running cmake...
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_TESTS=ON

after_build:
  - cd c:\projects\easy-cpp-print
  - ctest
