os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\easy-cpp-print

platform: x64
configuration: Release

install:

build:
  project: ALL_BUILD.vcxproj

before_build:
  - echo Downloading boost...
  - cd c:\projects\easy-cpp-print
  - cd include
  - curl -L -o boost.7z "http://netix.dl.sourceforge.net/project/boost/boost/1.46.0/boost_1_46_0.7z" 2> NUL 1> NUL
  - 7z -aoa x boost.7z > NUL
  - cd boost_1_46_0
  - move boost ..
  - cd ../..
  - echo Running cmake...
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_TESTS=ON

after_build:
  - cd c:\projects\easy-cpp-print
  - ctest
